version: '3.9'
services:
  notepad-rest-api:
    container_name: notepad-rest-api
    restart: unless-stopped
    environment:
      - NODE_ENV=dev
    ports:
      - '3100:3000'
    volumes:
      - ./express:/src
      - /src/node_modules
    build:
      context: ./express/
    command: npm run dev
    depends_on:
      - notepad-mongodb
  notepad-mongodb:
    image: mongo:5.0.9
    container_name: notepad-mongodb
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - ./express/mongo-volume:/data/db
      - ./express/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=mongo-dev
  faktory:
    image: contribsys/faktory:1.6.1
    container_name: faktory
    ports:
      - '7419-7420:7419-7420'
    volumes:
      - ./express/faktory-data:/var/lib/faktory
      - ./express/faktory-config:/etc/faktory
    environment:
      - FAKTORY_ENV=staging
      - FAKTORY_PASSWORD=12345