version: '3.9'
services:
  notepad-nextjs:
    container_name: notepad-nextjs
    restart: unless-stopped
    ports:
      - '3000:3000'
    build:
      context: ./nextjs/
    depends_on:
      - notepad-rest-api
  notepad-rest-api:
    container_name: notepad-rest-api
    restart: unless-stopped
    environment:
      - NODE_ENV=dev
    ports:
      - '3100:3000'
    build:
      context: ./express/
    depends_on:
      - notepad-mongodb
  notepad-mongodb:
    image: mongo:5.0.9
    container_name: notepad-mongodb
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - ./express/mongo-volume:/data/db
      - ./express/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=mongo-dev